apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
   name: node-ingress-tls
   namespace: interopnet
 spec:
   dnsNames:
   - node.glif.io
   issuerRef:
     group: cert-manager.io
     kind: ClusterIssuer
     name: letsencrypt-prod
   secretName: node-ingress-tls
